export const companyTypes = [
      { value: '', label: 'All' },
      { value: 'Partnership Independent', label: 'Partnership Independent' },
      { value: 'Partnership Parent Headquarters', label: 'Partnership Parent Headquarters' },
      { value: 'Private Independent', label: 'Private Independent' },
      { value: 'Private Independent Headquarters', label: 'Private Independent Headquarters' },
      { value: 'Private Parent', label: 'Private Parent' },
      { value: 'Private Parent Headquarters', label: 'Private Parent Headquarters' },
      { value: 'Public Independent', label: 'Public Independent' },
      { value: 'Public Parent Headquarters', label: 'Public Parent Headquarters' },
];

export const employeeRanges = [
      { value: '', label: 'All' },
      { value: '1-50', label: '1-50' },
      { value: '51-100', label: '51-100' },
      { value: '101-250', label: '101-250' },
      { value: '251-500', label: '251-500' },
      { value: '501-1,000', label: '501-1,000' },
      { value: '>1,000', label: '>1,000' },
];

export const salesRanges = [
      { value: '', label: 'All' },
      { value: '0', label: '0-10M' },
      { value: '10', label: '10M-50M' },
      { value: '50', label: '50M-100M' },
      { value: '100', label: '>100M' },
];
export const ownershipTypes = [
      { value: '', label: 'All' },
      { value: 'Non-Corporates', label: 'Non-Corporates' },
      { value: 'Nonprofit', label: 'Nonprofit' },
      { value: 'Partnership', label: 'Partnership' },
      { value: 'Private', label: 'Private' },
      { value: 'Public', label: 'Public' },
];
export const industries = [
      { label: 'All', value: '' },
      { label: 'Accounting and Tax Preparation', value: 'Accounting and Tax Preparation' },
      { label: 'Administrative Services', value: 'Administrative Services' },
      { label: 'Advertising Services', value: 'Advertising Services' },
      { label: 'Air Transportation Services', value: 'Air Transportation Services' },
      { label: 'Aircraft Engine and Parts Manufacturing', value: 'Aircraft Engine and Parts Manufacturing' },
      { label: 'Alcoholic Beverage Wholesale', value: 'Alcoholic Beverage Wholesale' },
      { label: 'Ambulatory Services', value: 'Ambulatory Services' },
      { label: 'Appliance Repair and Maintenance', value: 'Appliance Repair and Maintenance' },
      { label: 'Architecture and Engineering', value: 'Architecture and Engineering' },
      { label: 'Associations and Organizations', value: 'Associations and Organizations' },
      { label: 'Banking', value: 'Banking' },
      { label: 'Beverage Manufacturing', value: 'Beverage Manufacturing' },
      { label: 'Broadcasting and Media', value: 'Broadcasting and Media' },
      { label: 'Building and Dwelling Services', value: 'Building and Dwelling Services' },
      { label: 'Business Support Services', value: 'Business Support Services' },
      { label: 'Cement and Concrete Product Manufacturing', value: 'Cement and Concrete Product Manufacturing' },
      { label: 'Chemical Wholesale', value: 'Chemical Wholesale' },
      { label: 'Child Day Care Services', value: 'Child Day Care Services' },
      { label: 'Civil Engineering', value: 'Civil Engineering' },
      { label: 'Clothing and Apparel Manufacturing', value: 'Clothing and Apparel Manufacturing' },
      { label: 'Clothing and Apparel Stores', value: 'Clothing and Apparel Stores' },
      { label: 'Clothing and Apparel Wholesale', value: 'Clothing and Apparel Wholesale' },
      { label: 'Colleges and Universities', value: 'Colleges and Universities' },
      { label: 'Commercial and Industrial Rental', value: 'Commercial and Industrial Rental' },
      { label: 'Commercial Real Estate Leasing', value: 'Commercial Real Estate Leasing' },
      { label: 'Commodities', value: 'Commodities' },
      { label: 'Computer and Peripheral Equipment Manufacturing', value: 'Computer and Peripheral Equipment Manufacturing' },
      { label: 'Computer Programming', value: 'Computer Programming' },
      { label: 'Computer System Design Services', value: 'Computer System Design Services' },
      {
            label: 'Computer, Office Equipment and Software Merchant Wholesalers',
            value: 'Computer, Office Equipment and Software Merchant Wholesalers',
      },
      { label: 'Construction and Hardware Materials Wholesale', value: 'Construction and Hardware Materials Wholesale' },
      { label: 'Construction Machinery Manufacturing', value: 'Construction Machinery Manufacturing' },
      { label: 'Consulting Services', value: 'Consulting Services' },
      { label: 'Consumer Electronics Repair and Maintenance', value: 'Consumer Electronics Repair and Maintenance' },
      { label: 'Data Processing', value: 'Data Processing' },
      { label: 'Death Care Services', value: 'Death Care Services' },
      { label: 'Dentists', value: 'Dentists' },
      { label: 'Department Stores', value: 'Department Stores' },
      { label: 'Diagnostic Laboratories', value: 'Diagnostic Laboratories' },
      { label: 'Electrical Equipment and Appliances Manufacturing', value: 'Electrical Equipment and Appliances Manufacturing' },
      { label: 'Electricity Generation and Distribution', value: 'Electricity Generation and Distribution' },
      { label: 'Electronics and Appliances Stores', value: 'Electronics and Appliances Stores' },
      { label: 'Electronics Wholesale', value: 'Electronics Wholesale' },
      { label: 'Employment Services', value: 'Employment Services' },
      { label: 'Fitness and Recreation Centers', value: 'Fitness and Recreation Centers' },
      { label: 'Food Manufacturing', value: 'Food Manufacturing' },
      { label: 'Furniture Manufacturing', value: 'Furniture Manufacturing' },
      { label: 'Gasoline Stations and Fuel Dealers', value: 'Gasoline Stations and Fuel Dealers' },
      { label: 'Grocery Stores', value: 'Grocery Stores' },
      { label: 'Grocery Wholesale', value: 'Grocery Wholesale' },
      { label: 'Health and Personal Care Wholesale', value: 'Health and Personal Care Wholesale' },
      { label: 'Holding Companies', value: 'Holding Companies' },
      { label: 'Home and Garden Retail', value: 'Home and Garden Retail' },
      { label: 'Home Furnishings Retail', value: 'Home Furnishings Retail' },
      { label: 'Home Furnishings Wholesale', value: 'Home Furnishings Wholesale' },
      { label: 'Hospitals', value: 'Hospitals' },
      { label: 'Hotels and Accommodation', value: 'Hotels and Accommodation' },
      { label: 'Industrial Machinery Repair and Maintenance', value: 'Industrial Machinery Repair and Maintenance' },
      { label: 'Insurance Agents', value: 'Insurance Agents' },
      { label: 'Internet and Web Services', value: 'Internet and Web Services' },
      { label: 'Investigation and Security Services', value: 'Investigation and Security Services' },
      { label: 'Investment Services', value: 'Investment Services' },
      { label: 'Laundry Services', value: 'Laundry Services' },
      { label: 'Legal Services', value: 'Legal Services' },
      { label: 'Life and Health Insurance', value: 'Life and Health Insurance' },
      { label: 'Machinery and Equipment Manufacturing', value: 'Machinery and Equipment Manufacturing' },
      { label: 'Machinery Wholesale', value: 'Machinery Wholesale' },
      { label: 'Market Research and Opinion Polling', value: 'Market Research and Opinion Polling' },
      { label: 'Mass Transit and Ground Passenger Transportation', value: 'Mass Transit and Ground Passenger Transportation' },
      { label: 'Medical Equipment and Supplies', value: 'Medical Equipment and Supplies' },
      { label: 'Metal Products Manufacturing', value: 'Metal Products Manufacturing' },
      { label: 'Metals and Minerals Wholesale', value: 'Metals and Minerals Wholesale' },
      { label: 'Miscellaneous Amusement and Recreation', value: 'Miscellaneous Amusement and Recreation' },
      { label: 'Miscellaneous Chemical Manufacturing', value: 'Miscellaneous Chemical Manufacturing' },
      { label: 'Miscellaneous Educational Services', value: 'Miscellaneous Educational Services' },
      { label: 'Miscellaneous Manufacturing', value: 'Miscellaneous Manufacturing' },
      { label: 'Miscellaneous Personal Services', value: 'Miscellaneous Personal Services' },
      { label: 'Miscellaneous Professional Services', value: 'Miscellaneous Professional Services' },
      { label: 'Miscellaneous Store Retailers', value: 'Miscellaneous Store Retailers' },
      {
            label: 'Miscellaneous Transportation Equipment Manufacturing',
            value: 'Miscellaneous Transportation Equipment Manufacturing',
      },
      { label: 'Miscellaneous Wholesale', value: 'Miscellaneous Wholesale' },
      { label: 'Mortgage and Credit', value: 'Mortgage and Credit' },
      { label: 'Motor Vehicle and Parts Dealers', value: 'Motor Vehicle and Parts Dealers' },
      { label: 'Motor Vehicle Manufacturing', value: 'Motor Vehicle Manufacturing' },
      { label: 'Motor Vehicle Parts Manufacturing', value: 'Motor Vehicle Parts Manufacturing' },
      { label: 'Motor Vehicle Rental', value: 'Motor Vehicle Rental' },
      { label: 'Motor Vehicle Repair and Maintenance', value: 'Motor Vehicle Repair and Maintenance' },
      { label: 'Motor Vehicle Wholesale', value: 'Motor Vehicle Wholesale' },
      { label: 'Movies', value: 'Movies' },
      { label: 'Nonclassifiable Establishments', value: 'Nonclassifiable Establishments' },
      { label: 'Non-Metallic Mineral Product Manufacturing', value: 'Non-Metallic Mineral Product Manufacturing' },
      { label: 'Non-store Retail', value: 'Non-store Retail' },
      { label: 'Nursing and Residential Care', value: 'Nursing and Residential Care' },
      { label: 'Paper Product Manufacturing', value: 'Paper Product Manufacturing' },
      { label: 'Paper Wholesale', value: 'Paper Wholesale' },
      { label: 'Pensions and Funds', value: 'Pensions and Funds' },
      { label: 'Performing Arts', value: 'Performing Arts' },
      { label: 'Personal Care Services', value: 'Personal Care Services' },
      { label: 'Petroleum and Natural Gas Extraction', value: 'Petroleum and Natural Gas Extraction' },
      { label: 'Petroleum Product Manufacturing', value: 'Petroleum Product Manufacturing' },
      { label: 'Petroleum Wholesale', value: 'Petroleum Wholesale' },
      { label: 'Pharmaceutical Manufacturing', value: 'Pharmaceutical Manufacturing' },
      { label: 'Pharmacies and Personal Care Stores', value: 'Pharmacies and Personal Care Stores' },
      { label: 'Photofinishing', value: 'Photofinishing' },
      { label: 'Photographic Services', value: 'Photographic Services' },
      { label: 'Physicians and Health Practitioners', value: 'Physicians and Health Practitioners' },
      { label: 'Postal, Shipping and Messengers', value: 'Postal, Shipping and Messengers' },
      { label: 'Primary and Secondary Education', value: 'Primary and Secondary Education' },
      { label: 'Printing', value: 'Printing' },
      { label: 'Professional and Commercial Equipment Wholesale', value: 'Professional and Commercial Equipment Wholesale' },
      { label: 'Promoters and Agents', value: 'Promoters and Agents' },
      { label: 'Property and Casualty Insurance', value: 'Property and Casualty Insurance' },
      { label: 'Property Managers', value: 'Property Managers' },
      { label: 'Publishing', value: 'Publishing' },
      { label: 'Real Estate Agents and Brokers', value: 'Real Estate Agents and Brokers' },
      { label: 'Research and Development Services', value: 'Research and Development Services' },
      { label: 'Residential and Commercial Building Construction', value: 'Residential and Commercial Building Construction' },
      { label: 'Restaurants and Bars', value: 'Restaurants and Bars' },
      { label: 'Road Transportation Services', value: 'Road Transportation Services' },
      { label: 'Rubber and Plastic Product Manufacturing', value: 'Rubber and Plastic Product Manufacturing' },
      { label: 'Securities', value: 'Securities' },
      {
            label: 'Semiconductor and Other Electronic Component Manufacturing',
            value: 'Semiconductor and Other Electronic Component Manufacturing',
      },
      { label: 'Ship and Boat Building', value: 'Ship and Boat Building' },
      { label: 'Shipping and Water Transport', value: 'Shipping and Water Transport' },
      { label: 'Shipping and Water Transportation Services', value: 'Shipping and Water Transportation Services' },
      { label: 'Social and Rehabilitation Services', value: 'Social and Rehabilitation Services' },
      { label: 'Software', value: 'Software' },
      { label: 'Specialized Design Services', value: 'Specialized Design Services' },
      { label: 'Specialty Construction Trade Contractors', value: 'Specialty Construction Trade Contractors' },
      { label: 'Spectator Sports', value: 'Spectator Sports' },
      { label: 'Sporting Goods and Recreation Stores', value: 'Sporting Goods and Recreation Stores' },
      { label: 'Synthetic Chemical Manufacturing', value: 'Synthetic Chemical Manufacturing' },
      { label: 'Textile Manufacturing', value: 'Textile Manufacturing' },
      { label: 'Transportation Equipment Wholesale', value: 'Transportation Equipment Wholesale' },
      { label: 'Travel and Reservation Services', value: 'Travel and Reservation Services' },
      { label: 'Trucking', value: 'Trucking' },
      { label: 'Waste Management', value: 'Waste Management' },
      { label: 'Wired Telecommunications Carriers', value: 'Wired Telecommunications Carriers' },
      { label: 'Wireless Telecommunications Carriers', value: 'Wireless Telecommunications Carriers' },
      { label: 'Wood Product Manufacturing', value: 'Wood Product Manufacturing' },
];

export const regions = [
      {
            name: 'Africa',
            countries: [
                  'Algeria',
                  'Angola',
                  'Benin',
                  'Botswana',
                  'Burkina Faso',
                  'Burundi',
                  'Cameroon',
                  'Cape Verde',
                  'Central African Republic',
                  'Chad',
                  'Comoros',
                  'Congo (DRC)',
                  'Congo (Republic)',
                  'Djibouti',
                  'Egypt',
                  'Equatorial Guinea',
                  'Eritrea',
                  'Ethiopia',
                  'Gabon',
                  'Gambia',
                  'Ghana',
                  'Guinea',
                  'Guinea-Bissau',
                  'Kenya',
                  'Lesotho',
                  'Liberia',
                  'Libya',
                  'Madagascar',
                  'Malawi',
                  'Mali',
                  'Mauritania',
                  'Mauritius',
                  'Morocco',
                  'Mozambique',
                  'Namibia',
                  'Niger',
                  'Nigeria',
                  'Rwanda',
                  'Sao Tome and Principe',
                  'Senegal',
                  'Seychelles',
                  'Sierra Leone',
                  'Somalia',
                  'South Africa',
                  'Sudan',
                  'Swaziland',
                  'Tanzania',
                  'Togo',
                  'Tunisia',
                  'Uganda',
                  'Zambia',
                  'Zimbabwe',
            ],
      },
      {
            name: 'Asia',
            countries: [
                  'Afghanistan',
                  'Armenia',
                  'Azerbaijan',
                  'Bahrain',
                  'Bangladesh',
                  'Bhutan',
                  'Brunei Darussalam',
                  'Cambodia',
                  'China',
                  'Georgia',
                  'Hong Kong',
                  'India',
                  'Indonesia',
                  'Iran',
                  'Israel',
                  'Japan',
                  'Jordan',
                  'Kazakhstan',
                  'Kuwait',
                  'Kyrgyzstan',
                  'Laos',
                  'Lebanon',
                  'Malaysia',
                  'Maldives',
                  'Mongolia',
                  'Myanmar',
                  'Nepal',
                  'North Korea',
                  'Oman',
                  'Pakistan',
                  'Philippines',
                  'Qatar',
                  'Saudi Arabia',
                  'Singapore',
                  'South Korea',
                  'Sri Lanka',
                  'Syria',
                  'Taiwan',
                  'Tajikistan',
                  'Thailand',
                  'Turkey',
                  'Turkmenistan',
                  'United Arab Emirates',
                  'Uzbekistan',
                  'Vietnam',
                  'Yemen',
            ],
      },
      {
            name: 'Europe',
            countries: [
                  'Albania',
                  'Andorra',
                  'Austria',
                  'Belarus',
                  'Belgium',
                  'Bosnia Herzegovina',
                  'Bulgaria',
                  'Croatia',
                  'Cyprus',
                  'Czech Republic',
                  'Denmark',
                  'Estonia',
                  'Finland',
                  'France',
                  'Germany',
                  'Greece',
                  'Hungary',
                  'Iceland',
                  'Ireland',
                  'Italy',
                  'Latvia',
                  'Liechtenstein',
                  'Lithuania',
                  'Luxembourg',
                  'Malta',
                  'Moldova',
                  'Monaco',
                  'Netherlands',
                  'North Macedonia (FYROM)',
                  'Norway',
                  'Poland',
                  'Portugal',
                  'Romania',
                  'Russia',
                  'San Marino',
                  'Slovakia',
                  'Slovenia',
                  'Spain',
                  'Sweden',
                  'Switzerland',
                  'Ukraine',
                  'United Kingdom',
            ],
      },
      {
            name: 'North America',
            countries: [
                  'Antigua and Barbuda',
                  'Bahamas',
                  'Barbados',
                  'Belize',
                  'Canada',
                  'Costa Rica',
                  'Cuba',
                  'Dominica',
                  'Dominican Republic',
                  'El Salvador',
                  'Grenada',
                  'Guatemala',
                  'Haiti',
                  'Honduras',
                  'Jamaica',
                  'Mexico',
                  'Nicaragua',
                  'Panama',
                  'Saint Kitts and Nevis',
                  'Saint Vincent and the Grenadines',
                  'Trinidad and Tobago',
                  'United States',
            ],
      },
      {
            name: 'Oceania',
            countries: [
                  'Australia',
                  'Cook Islands',
                  'Fiji',
                  'Kiribati',
                  'New Zealand',
                  'Papua New Guinea',
                  'Samoa',
                  'Solomon Islands',
                  'Timor-Leste',
                  'Tonga',
                  'Vanuatu',
            ],
      },
      {
            name: 'South America',
            countries: [
                  'Argentina',
                  'Bolivia',
                  'Brazil',
                  'Chile',
                  'Colombia',
                  'Ecuador',
                  'Guyana',
                  'Paraguay',
                  'Peru',
                  'Suriname',
                  'Uruguay',
                  'Venezuela',
            ],
      },
];

export const functions = [
      { value: '', label: 'All' },
      { value: 'Admin', label: 'Admin' },
      { value: 'Finance', label: 'Finance' },
      { value: 'General', label: 'General' },
      { value: 'Human Resources', label: 'Human Resources' },
      { value: 'IT', label: 'IT' },
      { value: 'Marketing', label: 'Marketing' },
      { value: 'Procurement', label: 'Procurement' },
      { value: 'Sales', label: 'Sales' },
      { value: 'Legal and Compliance', label: 'Legal and Compliance' },
];

export const seniorityLevels = [
      { value: '', label: 'All' },
      { value: 'C-Level', label: 'C-Level' },
      { value: 'VP-Level', label: 'VP-Level' },
      { value: 'Director', label: 'Director' },
      { value: 'Manager', label: 'Manager' },
      { value: 'Non-Manager', label: 'Non-Manager' },
];
export const primaryIndustries = [
      { value: '', label: 'All' },
      { value: 'Agriculture', label: 'Agriculture' },
      { value: 'Business Services', label: 'Business Services' },
      { value: 'Construction', label: 'Construction' },
      { value: 'Consumer Services', label: 'Consumer Services' },
      { value: 'Education', label: 'Education' },
      { value: 'Energy, Utilities & Waste', label: 'Energy, Utilities & Waste' },
      { value: 'Finance', label: 'Finance' },
      { value: 'Government', label: 'Government' },
      { value: 'Healthcare Services', label: 'Healthcare Services' },
      { value: 'Holding Companies & Conglomerates', label: 'Holding Companies & Conglomerates' },
      { value: 'Hospitality', label: 'Hospitality' },
      { value: 'Hospitals & Physicians Clinics', label: 'Hospitals & Physicians Clinics' },
      { value: 'Insurance', label: 'Insurance' },
      { value: 'Law Firms & Legal Services', label: 'Law Firms & Legal Services' },
      { value: 'Manufacturing', label: 'Manufacturing' },
      { value: 'Media & Internet', label: 'Media & Internet' },
      { value: 'Minerals & Mining', label: 'Minerals & Mining' },
      { value: 'Organizations', label: 'Organizations' },
      { value: 'Real Estate', label: 'Real Estate' },
      { value: 'Retail', label: 'Retail' },
      { value: 'Software', label: 'Software' },
      { value: 'Telecommunications', label: 'Telecommunications' },
      { value: 'Transportation', label: 'Transportation' },
];

export const subIndustries = [
      { value: '', label: 'All' },
      { value: 'Animals & Livestock', label: 'Animals & Livestock' },
      { value: 'Crops', label: 'Crops' },
      { value: 'Forestry', label: 'Forestry' },
      { value: 'Accounting Services', label: 'Accounting Services' },
      { value: 'Advertising & Marketing', label: 'Advertising & Marketing' },
      { value: 'Call Centers & Business Centers', label: 'Call Centers & Business Centers' },
      { value: 'Chambers of Commerce', label: 'Chambers of Commerce' },
      { value: 'Commercial Printing', label: 'Commercial Printing' },
      { value: 'Custom Software & IT Services', label: 'Custom Software & IT Services' },
      { value: 'Debt Collection', label: 'Debt Collection' },
      { value: 'Facilities Management & Commercial Cleaning', label: 'Facilities Management & Commercial Cleaning' },
      { value: 'Food Service', label: 'Food Service' },
      { value: 'HR & Staffing', label: 'HR & Staffing' },
      { value: 'Information & Document Management', label: 'Information & Document Management' },
      { value: 'Management Consulting', label: 'Management Consulting' },
      { value: 'Multimedia & Graphic Design', label: 'Multimedia & Graphic Design' },
      { value: 'Research & Development', label: 'Research & Development' },
      { value: 'Security Products & Services', label: 'Security Products & Services' },
      { value: 'Translation & Linguistic Services', label: 'Translation & Linguistic Services' },
      { value: 'Architecture, Engineering & Design', label: 'Architecture, Engineering & Design' },
      { value: 'Civil Engineering Construction', label: 'Civil Engineering Construction' },
      { value: 'Commercial & Residential Construction', label: 'Commercial & Residential Construction' },
      { value: 'Automotive Service & Collision Repair', label: 'Automotive Service & Collision Repair' },
      { value: 'Barber Shops & Beauty Salons', label: 'Barber Shops & Beauty Salons' },
      { value: 'Car & Truck Rental', label: 'Car & Truck Rental' },
      { value: 'Childcare', label: 'Childcare' },
      { value: 'Cleaning Services', label: 'Cleaning Services' },
      { value: 'Funeral Homes & Funeral Related Services', label: 'Funeral Homes & Funeral Related Services' },
      { value: 'Landscape Services', label: 'Landscape Services' },
      { value: 'Photography Studio', label: 'Photography Studio' },
      { value: 'Repair Services', label: 'Repair Services' },
      { value: 'Weight & Health Management', label: 'Weight & Health Management' },
      { value: 'Colleges & Universities', label: 'Colleges & Universities' },
      { value: 'K-12 Schools', label: 'K-12 Schools' },
      { value: 'Training', label: 'Training' },
      { value: 'Electricity, Oil & Gas', label: 'Electricity, Oil & Gas' },
      { value: 'Oil & Gas Exploration & Services', label: 'Oil & Gas Exploration & Services' },
      {
            value: 'Waste Treatment, Environmental Services & Recycling',
            label: 'Waste Treatment, Environmental Services & Recycling',
      },
      { value: 'Water Treatment', label: 'Water Treatment' },
      { value: 'Banking', label: 'Banking' },
      { value: 'Credit Cards & Transaction Processing', label: 'Credit Cards & Transaction Processing' },
      { value: 'Investment Banking', label: 'Investment Banking' },
      { value: 'Lending & Brokerage', label: 'Lending & Brokerage' },
      { value: 'Venture Capital & Private Equity', label: 'Venture Capital & Private Equity' },
      { value: 'Federal', label: 'Federal' },
      { value: 'Local', label: 'Local' },
      { value: 'State', label: 'State' },
      { value: 'Tribal Nations', label: 'Tribal Nations' },
      { value: 'Ambulance Services', label: 'Ambulance Services' },
      { value: 'Blood & Organ Banks', label: 'Blood & Organ Banks' },
      { value: 'Elderly Care Services', label: 'Elderly Care Services' },
      { value: 'Medical Laboratories & Imaging Centers', label: 'Medical Laboratories & Imaging Centers' },
      { value: 'Mental Health & Rehabilitation Facilities', label: 'Mental Health & Rehabilitation Facilities' },
      { value: 'Veterinary Services', label: 'Veterinary Services' },
      { value: 'Amusement Parks, Arcades & Attractions', label: 'Amusement Parks, Arcades & Attractions' },
      { value: 'Cultural & Informational Centers', label: 'Cultural & Informational Centers' },
      { value: 'Fitness & Dance Facilities', label: 'Fitness & Dance Facilities' },
      { value: 'Gambling & Gaming', label: 'Gambling & Gaming' },
      { value: 'Libraries', label: 'Libraries' },
      { value: 'Lodging & Resorts', label: 'Lodging & Resorts' },
      { value: 'Movie Theaters', label: 'Movie Theaters' },
      { value: 'Museums & Art Galleries', label: 'Museums & Art Galleries' },
      { value: 'Performing Arts Theaters', label: 'Performing Arts Theaters' },
      { value: 'Restaurants', label: 'Restaurants' },
      { value: 'Sports Teams & Leagues', label: 'Sports Teams & Leagues' },
      { value: 'Travel Agencies & Services', label: 'Travel Agencies & Services' },
      { value: 'Zoos & National Parks', label: 'Zoos & National Parks' },
      { value: 'Dental Offices', label: 'Dental Offices' },
      { value: 'Medical & Surgical Hospitals', label: 'Medical & Surgical Hospitals' },
      { value: 'Medical Specialists', label: 'Medical Specialists' },
      { value: 'Physicians Clinics', label: 'Physicians Clinics' },
      { value: 'Aerospace & Defense', label: 'Aerospace & Defense' },
      { value: 'Appliances', label: 'Appliances' },
      { value: 'Automotive Parts', label: 'Automotive Parts' },
      { value: 'Boats & Submarines', label: 'Boats & Submarines' },
      { value: 'Building Materials', label: 'Building Materials' },
      { value: 'Chemicals & Related Products', label: 'Chemicals & Related Products' },
      { value: 'Cleaning Products', label: 'Cleaning Products' },
      { value: 'Computer Equipment & Peripherals', label: 'Computer Equipment & Peripherals' },
      { value: 'Cosmetics, Beauty Supply & Personal Care Products', label: 'Cosmetics, Beauty Supply & Personal Care Products' },
      { value: 'Electronics', label: 'Electronics' },
      { value: 'Food & Beverage', label: 'Food & Beverage' },
      { value: 'Furniture', label: 'Furniture' },
      { value: 'Glass & Clay', label: 'Glass & Clay' },
      { value: 'Hand, Power & Lawn-care Tools', label: 'Hand, Power & Lawn-care Tools' },
      { value: 'Health & Nutrition Products', label: 'Health & Nutrition Products' },
      { value: 'Household & Personal Products', label: 'Household & Personal Products' },
];

export const employeeTotals = [
      { value: '', label: 'All' },
      { value: '1-50', label: '1-50' },
      { value: '51-200', label: '51-200' },
      { value: '201-500', label: '201-500' },
      { value: '501-1,000', label: '501-1,000' },
      { value: '1,001-5,000', label: '1,001-5,000' },
      { value: '5,001-10,000', label: '5,001-10,000' },
      { value: '10,000+', label: '10,000+' },
];

export const sources = [
      { value: '', label: 'All' },
      { value: 'Zoominfo', label: 'Zoominfo' },
      { value: 'LinkedIn', label: 'LinkedIn' },
      { value: 'HKTDC', label: 'HKTDC' },
      { value: 'Reachin', label: 'Reachin' },
];
export const revenueRanges = [
      { value: '', label: 'All' },
      { value: '$1 bil. - $5 bil.', label: '$1 bil. - $5 bil.' },
      { value: '$1 mil. - $5 mil.', label: '$1 mil. - $5 mil.' },
      { value: '$10 mil. - $25 mil.', label: '$10 mil. - $25 mil.' },
      { value: '$100 mil. - $250 mil.', label: '$100 mil. - $250 mil.' },
      { value: '$25 mil. - $50 mil.', label: '$25 mil. - $50 mil.' },
      { value: '$250 mil. - $500 mil.', label: '$250 mil. - $500 mil.' },
      { value: '$5 mil. - $10 mil.', label: '$5 mil. - $10 mil.' },
      { value: '$50 mil. - $100 mil.', label: '$50 mil. - $100 mil.' },
      { value: '$500 mil. - $1 bil.', label: '$500 mil. - $1 bil.' },
      { value: '$500,000 - $1 mil.', label: '$500,000 - $1 mil.' },
      { value: 'Over $5 bil.', label: 'Over $5 bil.' },
      { value: 'Under $500,000', label: 'Under $500,000' },
];
