export const companyTypes = [
      { value: 'Partnership Independent', label: 'Partnership Independent' },
      { value: 'Partnership Parent Headquarters', label: 'Partnership Parent Headquarters' },
      { value: 'Private Independent', label: 'Private Independent' },
      { value: 'Private Independent Headquarters', label: 'Private Independent Headquarters' },
      { value: 'Private Parent', label: 'Private Parent' },
      { value: 'Private Parent Headquarters', label: 'Private Parent Headquarters' },
      { value: 'Public Independent', label: 'Public Independent' },
      { value: 'Public Parent Headquarters', label: 'Public Parent Headquarters' },
];

export const employeeRanges = [
      { value: '1-50', label: '1-50' },
      { value: '51-100', label: '51-100' },
      { value: '101-250', label: '101-250' },
      { value: '251-500', label: '251-500' },
      { value: '501-1,000', label: '501-1,000' },
      { value: '>1,000', label: '>1,000' },
];

export const salesRanges = [
      { value: '0-10M', label: '0-10M' },
      { value: '10M-50M', label: '10M-50M' },
      { value: '50M-100M', label: '50M-100M' },
      { value: '>100M', label: '>100M' },
];
export const ownershipTypes = [
      { value: 'Non-Corporates', label: 'Non-Corporates' },
      { value: 'Nonprofit', label: 'Nonprofit' },
      { value: 'Partnership', label: 'Partnership' },
      { value: 'Private', label: 'Private' },
      { value: 'Public', label: 'Public' },
];
export const industries = [
      'Accounting and Tax Preparation',
      'Administrative Services',
      'Advertising Services',
      'Air Transportation Services',
      'Aircraft Engine and Parts Manufacturing',
      'Alcoholic Beverage Wholesale',
      'Ambulatory Services',
      'Appliance Repair and Maintenance',
      'Architecture and Engineering',
      'Associations and Organizations',
      'Banking',
      'Beverage Manufacturing',
      'Broadcasting and Media',
      'Building and Dwelling Services',
      'Business Support Services',
      'Cement and Concrete Product Manufacturing',
      'Chemical Wholesale',
      'Child Day Care Services',
      'Civil Engineering',
      'Clothing and Apparel Manufacturing',
      'Clothing and Apparel Stores',
      'Clothing and Apparel Wholesale',
      'Colleges and Universities',
      'Commercial and Industrial Rental',
      'Commercial Real Estate Leasing',
      'Commodities',
      'Computer and Peripheral Equipment Manufacturing',
      'Computer Programming',
      'Computer System Design Services',
      'Computer, Office Equipment and Software Merchant Wholesalers',
      'Construction and Hardware Materials Wholesale',
      'Construction Machinery Manufacturing',
      'Consulting Services',
      'Consumer Electronics Repair and Maintenance',
      'Data Processing',
      'Death Care Services',
      'Dentists',
      'Department Stores',
      'Diagnostic Laboratories',
      'Electrical Equipment and Appliances Manufacturing',
      'Electricity Generation and Distribution',
      'Electronics and Appliances Stores',
      'Electronics Wholesale',
      'Employment Services',
      'Fitness and Recreation Centers',
      'Food Manufacturing',
      'Furniture Manufacturing',
      'Gasoline Stations and Fuel Dealers',
      'Grocery Stores',
      'Grocery Wholesale',
      'Health and Personal Care Wholesale',
      'Holding Companies',
      'Home and Garden Retail',
      'Home Furnishings Retail',
      'Home Furnishings Wholesale',
      'Hospitals',
      'Hotels and Accommodation',
      'Industrial Machinery Repair and Maintenance',
      'Insurance Agents',
      'Internet and Web Services',
      'Investigation and Security Services',
      'Investment Services',
      'Laundry Services',
      'Legal Services',
      'Life and Health Insurance',
      'Machinery and Equipment Manufacturing',
      'Machinery Wholesale',
      'Market Research and Opinion Polling',
      'Mass Transit and Ground Passenger Transportation',
      'Medical Equipment and Supplies',
      'Metal Products Manufacturing',
      'Metals and Minerals Wholesale',
      'Miscellaneous Amusement and Recreation',
      'Miscellaneous Chemical Manufacturing',
      'Miscellaneous Educational Services',
      'Miscellaneous Manufacturing',
      'Miscellaneous Personal Services',
      'Miscellaneous Professional Services',
      'Miscellaneous Store Retailers',
      'Miscellaneous Transportation Equipment Manufacturing',
      'Miscellaneous Wholesale',
      'Mortgage and Credit',
      'Motor Vehicle and Parts Dealers',
      'Motor Vehicle Manufacturing',
      'Motor Vehicle Parts Manufacturing',
      'Motor Vehicle Rental',
      'Motor Vehicle Repair and Maintenance',
      'Motor Vehicle Wholesale',
      'Movies',
      'Nonclassifiable Establishments',
      'Non-Metallic Mineral Product Manufacturing',
      'Non-store Retail',
      'Nursing and Residential Care',
      'Paper Product Manufacturing',
      'Paper Wholesale',
      'Pensions and Funds',
      'Performing Arts',
      'Personal Care Services',
      'Petroleum and Natural Gas Extraction',
      'Petroleum Product Manufacturing',
      'Petroleum Wholesale',
      'Pharmaceutical Manufacturing',
      'Pharmacies and Personal Care Stores',
      'Photofinishing',
      'Photographic Services',
      'Physicians and Health Practitioners',
      'Postal, Shipping and Messengers',
      'Primary and Secondary Education',
      'Printing',
      'Professional and Commercial Equipment Wholesale',
      'Promoters and Agents',
      'Property and Casualty Insurance',
      'Property Managers',
      'Publishing',
      'Real Estate Agents and Brokers',
      'Research and Development Services',
      'Residential and Commercial Building Construction',
      'Restaurants and Bars',
      'Road Transportation Services',
      'Rubber and Plastic Product Manufacturing',
      'Securities',
      'Semiconductor and Other Electronic Component Manufacturing',
      'Ship and Boat Building',
      'Shipping and Water Transport',
      'Shipping and Water Transportation Services',
      'Social and Rehabilitation Services',
      'Software',
      'Specialized Design Services',
      'Specialty Construction Trade Contractors',
      'Spectator Sports',
      'Sporting Goods and Recreation Stores',
      'Synthetic Chemical Manufacturing',
      'Textile Manufacturing',
      'Transportation Equipment Wholesale',
      'Travel and Reservation Services',
      'Trucking',
      'Waste Management',
      'Wired Telecommunications Carriers',
      'Wireless Telecommunications Carriers',
      'Wood Product Manufacturing',
];

export const regions = [
      {
            name: 'Africa',
            countries: [
                  'Algeria',
                  'Angola',
                  'Benin',
                  'Botswana',
                  'Burkina Faso',
                  'Burundi',
                  'Cameroon',
                  'Cape Verde',
                  'Central African Republic',
                  'Chad',
                  'Comoros',
                  'Congo (DRC)',
                  'Congo (Republic)',
                  'Djibouti',
                  'Egypt',
                  'Equatorial Guinea',
                  'Eritrea',
                  'Ethiopia',
                  'Gabon',
                  'Gambia',
                  'Ghana',
                  'Guinea',
                  'Guinea-Bissau',
                  'Kenya',
                  'Lesotho',
                  'Liberia',
                  'Libya',
                  'Madagascar',
                  'Malawi',
                  'Mali',
                  'Mauritania',
                  'Mauritius',
                  'Morocco',
                  'Mozambique',
                  'Namibia',
                  'Niger',
                  'Nigeria',
                  'Rwanda',
                  'Sao Tome and Principe',
                  'Senegal',
                  'Seychelles',
                  'Sierra Leone',
                  'Somalia',
                  'South Africa',
                  'Sudan',
                  'Swaziland',
                  'Tanzania',
                  'Togo',
                  'Tunisia',
                  'Uganda',
                  'Zambia',
                  'Zimbabwe',
            ],
      },
      {
            name: 'Asia',
            countries: [
                  'Afghanistan',
                  'Armenia',
                  'Azerbaijan',
                  'Bahrain',
                  'Bangladesh',
                  'Bhutan',
                  'Brunei Darussalam',
                  'Cambodia',
                  'China',
                  'Georgia',
                  'Hong Kong',
                  'India',
                  'Indonesia',
                  'Iran',
                  'Israel',
                  'Japan',
                  'Jordan',
                  'Kazakhstan',
                  'Kuwait',
                  'Kyrgyzstan',
                  'Laos',
                  'Lebanon',
                  'Malaysia',
                  'Maldives',
                  'Mongolia',
                  'Myanmar',
                  'Nepal',
                  'North Korea',
                  'Oman',
                  'Pakistan',
                  'Philippines',
                  'Qatar',
                  'Saudi Arabia',
                  'Singapore',
                  'South Korea',
                  'Sri Lanka',
                  'Syria',
                  'Taiwan',
                  'Tajikistan',
                  'Thailand',
                  'Turkey',
                  'Turkmenistan',
                  'United Arab Emirates',
                  'Uzbekistan',
                  'Vietnam',
                  'Yemen',
            ],
      },
      {
            name: 'Europe',
            countries: [
                  'Albania',
                  'Andorra',
                  'Austria',
                  'Belarus',
                  'Belgium',
                  'Bosnia Herzegovina',
                  'Bulgaria',
                  'Croatia',
                  'Cyprus',
                  'Czech Republic',
                  'Denmark',
                  'Estonia',
                  'Finland',
                  'France',
                  'Germany',
                  'Greece',
                  'Hungary',
                  'Iceland',
                  'Ireland',
                  'Italy',
                  'Latvia',
                  'Liechtenstein',
                  'Lithuania',
                  'Luxembourg',
                  'Malta',
                  'Moldova',
                  'Monaco',
                  'Netherlands',
                  'North Macedonia (FYROM)',
                  'Norway',
                  'Poland',
                  'Portugal',
                  'Romania',
                  'Russia',
                  'San Marino',
                  'Slovakia',
                  'Slovenia',
                  'Spain',
                  'Sweden',
                  'Switzerland',
                  'Ukraine',
                  'United Kingdom',
            ],
      },
      {
            name: 'North America',
            countries: [
                  'Antigua and Barbuda',
                  'Bahamas',
                  'Barbados',
                  'Belize',
                  'Canada',
                  'Costa Rica',
                  'Cuba',
                  'Dominica',
                  'Dominican Republic',
                  'El Salvador',
                  'Grenada',
                  'Guatemala',
                  'Haiti',
                  'Honduras',
                  'Jamaica',
                  'Mexico',
                  'Nicaragua',
                  'Panama',
                  'Saint Kitts and Nevis',
                  'Saint Vincent and the Grenadines',
                  'Trinidad and Tobago',
                  'United States',
            ],
      },
      {
            name: 'Oceania',
            countries: [
                  'Australia',
                  'Cook Islands',
                  'Fiji',
                  'Kiribati',
                  'New Zealand',
                  'Papua New Guinea',
                  'Samoa',
                  'Solomon Islands',
                  'Timor-Leste',
                  'Tonga',
                  'Vanuatu',
            ],
      },
      {
            name: 'South America',
            countries: [
                  'Argentina',
                  'Bolivia',
                  'Brazil',
                  'Chile',
                  'Colombia',
                  'Ecuador',
                  'Guyana',
                  'Paraguay',
                  'Peru',
                  'Suriname',
                  'Uruguay',
                  'Venezuela',
            ],
      },
];

export const functions = [
      { value: 'Admin', label: 'Admin' },
      { value: 'Finance', label: 'Finance' },
      { value: 'General', label: 'General' },
      { value: 'Human Resources', label: 'Human Resources' },
      { value: 'IT', label: 'IT' },
      { value: 'Marketing', label: 'Marketing' },
      { value: 'Procurement', label: 'Procurement' },
      { value: 'Sales', label: 'Sales' },
      { value: 'Legal and Compliance', label: 'Legal and Compliance' },
];

export const seniorityLevels = [
      { value: 'C-Level', label: 'C-Level' },
      { value: 'VP-Level', label: 'VP-Level' },
      { value: 'Director', label: 'Director' },
      { value: 'Manager', label: 'Manager' },
      { value: 'Non-Manager', label: 'Non-Manager' },
];
export const primaryIndustries = [
      { value: 'Agriculture', label: 'Agriculture' },
      { value: 'Business Services', label: 'Business Services' },
      { value: 'Construction', label: 'Construction' },
      { value: 'Consumer Services', label: 'Consumer Services' },
      { value: 'Education', label: 'Education' },
      { value: 'Energy, Utilities & Waste', label: 'Energy, Utilities & Waste' },
      { value: 'Finance', label: 'Finance' },
      { value: 'Government', label: 'Government' },
      { value: 'Healthcare Services', label: 'Healthcare Services' },
      { value: 'Holding Companies & Conglomerates', label: 'Holding Companies & Conglomerates' },
      { value: 'Hospitality', label: 'Hospitality' },
      { value: 'Hospitals & Physicians Clinics', label: 'Hospitals & Physicians Clinics' },
      { value: 'Insurance', label: 'Insurance' },
      { value: 'Law Firms & Legal Services', label: 'Law Firms & Legal Services' },
      { value: 'Manufacturing', label: 'Manufacturing' },
      { value: 'Media & Internet', label: 'Media & Internet' },
      { value: 'Minerals & Mining', label: 'Minerals & Mining' },
      { value: 'Organizations', label: 'Organizations' },
      { value: 'Real Estate', label: 'Real Estate' },
      { value: 'Retail', label: 'Retail' },
      { value: 'Software', label: 'Software' },
      { value: 'Telecommunications', label: 'Telecommunications' },
      { value: 'Transportation', label: 'Transportation' },
];

export const subIndustries = [
      { value: 'Animals & Livestock', label: 'Animals & Livestock' },
      { value: 'Crops', label: 'Crops' },
      { value: 'Forestry', label: 'Forestry' },
      { value: 'Accounting Services', label: 'Accounting Services' },
      { value: 'Advertising & Marketing', label: 'Advertising & Marketing' },
      { value: 'Call Centers & Business Centers', label: 'Call Centers & Business Centers' },
      { value: 'Chambers of Commerce', label: 'Chambers of Commerce' },
      { value: 'Commercial Printing', label: 'Commercial Printing' },
      { value: 'Custom Software & IT Services', label: 'Custom Software & IT Services' },
      { value: 'Debt Collection', label: 'Debt Collection' },
      { value: 'Facilities Management & Commercial Cleaning', label: 'Facilities Management & Commercial Cleaning' },
      { value: 'Food Service', label: 'Food Service' },
      { value: 'HR & Staffing', label: 'HR & Staffing' },
      { value: 'Information & Document Management', label: 'Information & Document Management' },
      { value: 'Management Consulting', label: 'Management Consulting' },
      { value: 'Multimedia & Graphic Design', label: 'Multimedia & Graphic Design' },
      { value: 'Research & Development', label: 'Research & Development' },
      { value: 'Security Products & Services', label: 'Security Products & Services' },
      { value: 'Translation & Linguistic Services', label: 'Translation & Linguistic Services' },
      { value: 'Architecture, Engineering & Design', label: 'Architecture, Engineering & Design' },
      { value: 'Civil Engineering Construction', label: 'Civil Engineering Construction' },
      { value: 'Commercial & Residential Construction', label: 'Commercial & Residential Construction' },
      { value: 'Automotive Service & Collision Repair', label: 'Automotive Service & Collision Repair' },
      { value: 'Barber Shops & Beauty Salons', label: 'Barber Shops & Beauty Salons' },
      { value: 'Car & Truck Rental', label: 'Car & Truck Rental' },
      { value: 'Childcare', label: 'Childcare' },
      { value: 'Cleaning Services', label: 'Cleaning Services' },
      { value: 'Funeral Homes & Funeral Related Services', label: 'Funeral Homes & Funeral Related Services' },
      { value: 'Landscape Services', label: 'Landscape Services' },
      { value: 'Photography Studio', label: 'Photography Studio' },
      { value: 'Repair Services', label: 'Repair Services' },
      { value: 'Weight & Health Management', label: 'Weight & Health Management' },
      { value: 'Colleges & Universities', label: 'Colleges & Universities' },
      { value: 'K-12 Schools', label: 'K-12 Schools' },
      { value: 'Training', label: 'Training' },
      { value: 'Electricity, Oil & Gas', label: 'Electricity, Oil & Gas' },
      { value: 'Oil & Gas Exploration & Services', label: 'Oil & Gas Exploration & Services' },
      {
            value: 'Waste Treatment, Environmental Services & Recycling',
            label: 'Waste Treatment, Environmental Services & Recycling',
      },
      { value: 'Water Treatment', label: 'Water Treatment' },
      { value: 'Banking', label: 'Banking' },
      { value: 'Credit Cards & Transaction Processing', label: 'Credit Cards & Transaction Processing' },
      { value: 'Investment Banking', label: 'Investment Banking' },
      { value: 'Lending & Brokerage', label: 'Lending & Brokerage' },
      { value: 'Venture Capital & Private Equity', label: 'Venture Capital & Private Equity' },
      { value: 'Federal', label: 'Federal' },
      { value: 'Local', label: 'Local' },
      { value: 'State', label: 'State' },
      { value: 'Tribal Nations', label: 'Tribal Nations' },
      { value: 'Ambulance Services', label: 'Ambulance Services' },
      { value: 'Blood & Organ Banks', label: 'Blood & Organ Banks' },
      { value: 'Elderly Care Services', label: 'Elderly Care Services' },
      { value: 'Medical Laboratories & Imaging Centers', label: 'Medical Laboratories & Imaging Centers' },
      { value: 'Mental Health & Rehabilitation Facilities', label: 'Mental Health & Rehabilitation Facilities' },
      { value: 'Veterinary Services', label: 'Veterinary Services' },
      { value: 'Amusement Parks, Arcades & Attractions', label: 'Amusement Parks, Arcades & Attractions' },
      { value: 'Cultural & Informational Centers', label: 'Cultural & Informational Centers' },
      { value: 'Fitness & Dance Facilities', label: 'Fitness & Dance Facilities' },
      { value: 'Gambling & Gaming', label: 'Gambling & Gaming' },
      { value: 'Libraries', label: 'Libraries' },
      { value: 'Lodging & Resorts', label: 'Lodging & Resorts' },
      { value: 'Movie Theaters', label: 'Movie Theaters' },
      { value: 'Museums & Art Galleries', label: 'Museums & Art Galleries' },
      { value: 'Performing Arts Theaters', label: 'Performing Arts Theaters' },
      { value: 'Restaurants', label: 'Restaurants' },
      { value: 'Sports Teams & Leagues', label: 'Sports Teams & Leagues' },
      { value: 'Travel Agencies & Services', label: 'Travel Agencies & Services' },
      { value: 'Zoos & National Parks', label: 'Zoos & National Parks' },
      { value: 'Dental Offices', label: 'Dental Offices' },
      { value: 'Medical & Surgical Hospitals', label: 'Medical & Surgical Hospitals' },
      { value: 'Medical Specialists', label: 'Medical Specialists' },
      { value: 'Physicians Clinics', label: 'Physicians Clinics' },
      { value: 'Aerospace & Defense', label: 'Aerospace & Defense' },
      { value: 'Appliances', label: 'Appliances' },
      { value: 'Automotive Parts', label: 'Automotive Parts' },
      { value: 'Boats & Submarines', label: 'Boats & Submarines' },
      { value: 'Building Materials', label: 'Building Materials' },
      { value: 'Chemicals & Related Products', label: 'Chemicals & Related Products' },
      { value: 'Cleaning Products', label: 'Cleaning Products' },
      { value: 'Computer Equipment & Peripherals', label: 'Computer Equipment & Peripherals' },
      { value: 'Cosmetics, Beauty Supply & Personal Care Products', label: 'Cosmetics, Beauty Supply & Personal Care Products' },
      { value: 'Electronics', label: 'Electronics' },
      { value: 'Food & Beverage', label: 'Food & Beverage' },
      { value: 'Furniture', label: 'Furniture' },
      { value: 'Glass & Clay', label: 'Glass & Clay' },
      { value: 'Hand, Power & Lawn-care Tools', label: 'Hand, Power & Lawn-care Tools' },
      { value: 'Health & Nutrition Products', label: 'Health & Nutrition Products' },
      { value: 'Household & Personal Products', label: 'Household & Personal Products' },
];

export const employeeTotals = [
      { value: '1-50', label: '1-50' },
      { value: '51-200', label: '51-200' },
      { value: '201-500', label: '201-500' },
      { value: '501-1,000', label: '501-1,000' },
      { value: '1,001-5,000', label: '1,001-5,000' },
      { value: '5,001-10,000', label: '5,001-10,000' },
      { value: '10,000+', label: '10,000+' },
];

export const sources = [
      { value: 'Zoominfo', label: 'Zoominfo' },
      { value: 'LinkedIn', label: 'LinkedIn' },
      { value: 'HKTDC', label: 'HKTDC' },
      { value: 'Reachin', label: 'Reachin' },
];
export const revenueRanges = [
      { value: '$1 bil. - $5 bil.', label: '$1 bil. - $5 bil.' },
      { value: '$1 mil. - $5 mil.', label: '$1 mil. - $5 mil.' },
      { value: '$10 mil. - $25 mil.', label: '$10 mil. - $25 mil.' },
      { value: '$100 mil. - $250 mil.', label: '$100 mil. - $250 mil.' },
      { value: '$25 mil. - $50 mil.', label: '$25 mil. - $50 mil.' },
      { value: '$250 mil. - $500 mil.', label: '$250 mil. - $500 mil.' },
      { value: '$5 mil. - $10 mil.', label: '$5 mil. - $10 mil.' },
      { value: '$50 mil. - $100 mil.', label: '$50 mil. - $100 mil.' },
      { value: '$500 mil. - $1 bil.', label: '$500 mil. - $1 bil.' },
      { value: '$500,000 - $1 mil.', label: '$500,000 - $1 mil.' },
      { value: 'Over $5 bil.', label: 'Over $5 bil.' },
      { value: 'Under $500,000', label: 'Under $500,000' },
];
